### ISSUE TITLE
How can I generate without -1 and  Label with accurate time information?

### ISSUE THREAD

**Issue by yuuSiVo** [hyperzlib/Sinsy-Remix#10]
How can I generate without -1 and  Label with accurate time information?

![image](https://user-images.githubusercontent.com/26115406/69472981-5f48a880-0df4-11ea-8f34-d0d3f83b869d.png)

this time information is too bad

The time information is the same for consonants. Is there a way to fix this?

**Comment by hyperzlib** [comment]
-1 means generate time from model.

**Comment by hyperzlib** [comment]
you should use speech align tools to generate the 'mono label' for train.
