### ISSUE TITLE
Can we add English support to sinsy?

### ISSUE THREAD

**Issue by ElonSatoshi** [hyperzlib/Sinsy-Remix#2]

**Comment by 740291272** [comment]
yes

**Comment by YuzukiTsuru** [comment]
I just fix it in english use espeak-ng library

**Comment by hyperzlib** [comment]
Hello, I'm writing English support for Sinsy-Remix now. Could you help me?

**Comment by YuzukiTsuru** [comment]
no,go away!
I just make Hts Working with itself without sinsy front end lol

**Comment by YuzukiTsuru** [comment]
and the English dict is not the best way for     sinsy parser, there's some paper for use it with htsapi but not sinsy parser
