### ISSUE TITLE
Strange output

### ISSUE THREAD

**Issue by jedi2light** [hyperzlib/Sinsy-Remix#7]
I use the next hts voice files:
https://sourceforge.net/projects/sinsy/files/HTS%20voice/hts_voice_nitech_jp_song070_f001-0.90/
https://sourceforge.net/projects/mmdagent/files/MMDAgent_Example/
I use self-compiled sinsy by this way:
`./bin/sinsy -w j -x $PWD/dic/ -m mei_happy.htsvoice  -o ~/Desktop/cdecdc.wav -l d  ~/Desktop/cdecdc.xml`
But... when I listen output file there is a very big difference with file which generated by sinsy web page
Should I use another hts voice file? But where I can find and download them for free?

**Comment by muzea** [comment]
- The open source version of Sinsy lags behind the version used by the official website.
- Some models used in the official website are not available for download.

**Comment by jedi2light** [comment]
Oh, thank you for your quick reply
