### ISSUE TITLE
Where to get voice files?

### ISSUE THREAD

**Issue by alex-tee** [hyperzlib/Sinsy-Remix#8]
Hi, the only voice file i can find is the one that comes with the original Sinsy. Where can I find other voice files?

**Comment by hyperzlib** [comment]
Not any other trained htsvoice now.
You could train new htsvoice use the original train pack: http://hts.sp.nitech.ac.jp/archives/2.3/HTS-demo_NIT-SONG070-F001.tar.bz2
This project may help you complie 'question.hed' file: https://github.com/hyperzlib/hts-label-format-generator
